In [1]:
import pandas as pd
import numpy as np

leemos los csv de los datos sobre los que tenemos que trabajar

In [2]:
amazon_df = pd.read_csv('Datasets/amazon_prime_titles-score.csv')
disney_df = pd.read_csv('Datasets/disney_plus_titles-score.csv')
hulu_df = pd.read_csv('Datasets/hulu_titles-score (2).csv')
netflix_df = pd.read_csv('Datasets/netflix_titles-score.csv')

los mostramos para ver que se hayan cargado bien y para saber que columnas hay, cuantas filas hay, y para tener un vistazo sobre el tipo de contenido y control sobre los cambios que vamos a realizar

In [13]:
amazon_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score,id,duration_int,duration_type,platform
0,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,99,as1,113,min,amazon
1,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,37,as2,110,min,amazon
2,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,20,as3,74,min,amazon
3,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,g,69 min,documentary,"pink breaks the mold once again, bringing her ...",27,as4,69,min,amazon
4,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,75,as5,45,min,amazon

In [14]:
disney_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score,id,duration_int,duration_type,platform
0,s1,movie,duck the halls: a mickey mouse christmas special,"alonso ramirez ramos, dave wasson","chris diamantopoulos, tony anselmo, tress macn...",NaN,2021-11-26,2016,tv-g,23 min,"animation, family",join mickey and the gang as they duck the halls!,100,ds1,23,min,disney
1,s2,movie,ernest saves christmas,john cherry,"jim varney, noelle parker, douglas seale",NaN,2021-11-26,1988,pg,91 min,comedy,santa claus passes his magic bag to a new st. ...,17,ds2,91,min,disney
2,s3,movie,ice age: a mammoth christmas,karen disher,"raymond albert romano, john leguizamo, denis l...",united states,2021-11-26,2011,tv-g,23 min,"animation, comedy, family",sid the sloth is on santa's naughty list.,92,ds3,23,min,disney
3,s4,movie,the queen family singalong,hamish hamilton,"darren criss, adam lambert, derek hough, alexa...",NaN,2021-11-26,2021,tv-pg,41 min,musical,"this is real life, not just fantasy!",35,ds4,41,min,disney
4,s5,tv show,the beatles: get back,NaN,"john lennon, paul mccartney, george harrison, ...",NaN,2021-11-25,2021,g,1 season,"docuseries, historical, music",a three-part documentary from peter jackson ca...,11,ds5,1,season,disney

In [15]:
hulu_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score,id,duration_int,duration_type,platform
0,s1,movie,ricky velez: here's everything,NaN,NaN,NaN,2021-10-24,2021,tv-ma,0 min,"comedy, stand up",​comedian ricky velez bares it all with his ho...,48,hs1,0,min,hulu
1,s2,movie,silent night,NaN,NaN,NaN,2021-10-23,2020,g,94 min,"crime, drama, thriller","mark, a low end south london hitman recently r...",8,hs2,94,min,hulu
2,s3,movie,the marksman,NaN,NaN,NaN,2021-10-23,2021,pg-13,108 min,"action, thriller",a hardened arizona rancher tries to protect an...,8,hs3,108,min,hulu
3,s4,movie,gaia,NaN,NaN,NaN,2021-10-22,2021,r,97 min,horror,a forest ranger and two survivalists with a cu...,33,hs4,97,min,hulu
4,s5,movie,settlers,NaN,NaN,NaN,2021-10-22,2021,g,104 min,"science fiction, thriller",mankind's earliest settlers on the martian fro...,24,hs5,104,min,hulu

In [16]:
#netflix_df.head()
netflix_df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score,id,duration_int,duration_type,platform
0,s1,movie,dick johnson is dead,kirsten johnson,NaN,united states,2021-09-25,2020,pg-13,90 min,documentaries,"as her father nears the end of his life, filmm...",29,ns1,90,min,netflix
1,s2,tv show,blood & water,NaN,"ama qamata, khosi ngema, gail mabalane, thaban...",south africa,2021-09-24,2021,tv-ma,2 seasons,"international tv shows, tv dramas, tv mysteries","after crossing paths at a party, a cape town t...",86,ns2,2,season,netflix
2,s3,tv show,ganglands,julien leclercq,"sami bouajila, tracy gotoas, samuel jouy, nabi...",NaN,2021-09-24,2021,tv-ma,1 season,"crime tv shows, international tv shows, tv act...",to protect his family from a powerful drug lor...,75,ns3,1,season,netflix
3,s4,tv show,jailbirds new orleans,NaN,NaN,NaN,2021-09-24,2021,tv-ma,1 season,"docuseries, reality tv","feuds, flirtations and toilet talk go down amo...",49,ns4,1,season,netflix
4,s5,tv show,kota factory,NaN,"mayur more, jitendra kumar, ranjan raj, alam k...",india,2021-09-24,2021,tv-ma,2 seasons,"international tv shows, romantic tv shows, tv ...",in a city of coaching centers known to train i...,92,ns5,2,season,netflix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,movie,zodiac,david fincher,"mark ruffalo, jake gyllenhaal, robert downey j...",united states,2019-11-20,2007,r,158 min,"cult movies, dramas, thrillers","a political cartoonist, a crime reporter and a...",20,ns8803,158,min,netflix
8803,s8804,tv show,zombie dumb,NaN,NaN,NaN,2019-07-01,2018,tv-y7,2 seasons,"kids' tv, korean tv shows, tv comedies","while living alone in a spooky town, a young g...",8,ns8804,2,season,netflix
8804,s8805,movie,zombieland,ruben fleischer,"jesse eisenberg, woody harrelson, emma stone, ...",united states,2019-11-01,2009,r,88 min,"comedies, horror movies",looking to survive in a world taken over by zo...,55,ns8805,88,min,netflix
8805,s8806,movie,zoom,peter hewitt,"tim allen, courteney cox, chevy chase, kate ma...",united states,2020-01-11,2006,pg,88 min,"children & family movies, comedies","dragged from civilian life, a former superhero...",7,ns8806,88,min,netflix
8806,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019-03-02,2015,tv-14,111 min,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,44,ns8807,111,min,netflix

voy a crear 3 listas, una con los dataframes, otra con las plataformas y otra con las iniciales, las cuales van a ser utilizadas posteriormente en las distintas fucniones de transformacion. las creo ahora y en orden para no olvidarme despues y ya queden hechas.

In [8]:
# Crear una lista de DataFrames, plataformas y sus respectivas iniciales en el mismo orden
dataframes = [netflix_df, disney_df, hulu_df, amazon_df]
platforms = ['netflix', 'disney', 'hulu', 'amazon']
letters = ['n', 'd', 'h', 'a']

Transformacion sobre las fechas: De haber fechas, deberán tener el formato **`AAAA-mm-dd`**

In [4]:


def date_format(dataframe: pd.DataFrame, date_column: str):
    """
    Cambia el formato de la fecha en una columna especificada de un DataFrame de "nombre del mes dd, yyyy" a "yyyy-mm-dd"
    """
    # Remover espacios en blanco en las fechas
    dataframe[date_column] = dataframe[date_column].str.strip()
    # Cambiar el formato de la fecha
    dataframe[date_column] = pd.to_datetime(dataframe[date_column], format='%B %d, %Y')
    dataframe[date_column] = dataframe[date_column].dt.strftime('%Y-%m-%d')


# Aplicar la función date_format a cada DataFrame en la lista
for df in dataframes:
    date_format(df, 'date_added')

Creacion de la columna ID con los criterios que se nos pidieron

Generar campo **`id`**: Cada id se compondrá de la primera letra del nombre de la plataforma,
seguido del show_id ya presente en los datasets (ejemplo para títulos de Amazon = **`as123`**)

In [5]:
def add_id_column(dataframe: pd.DataFrame, letter: str):
    """
    Agrega una nueva columna "id" al principio del contenido de la columna "show_id" en un DataFrame.
    """
    dataframe["id"] = letter+dataframe["show_id"]


# Aplicar la función add_id_column a cada DataFrame en la lista con la letra correspondiente
for i, df in enumerate(dataframes):
    add_id_column(df, letters[i])

Transformacion sobre los valores nulos de la columna "Rating"
Los valores nulos del campo rating deberán reemplazarse por el string “**`G`**” (corresponde al maturity rating: “general for all audiences”

In [6]:
def replace_nan(dataframe: pd.DataFrame, value: str, column: str):
    """
    Reemplaza los valores nulos en una columna especificada del DataFrame con un valor especificado.
    """
    dataframe[column].fillna(value=value, inplace=True)
    


# Aplicar la función replace_nan a cada DataFrame en la lista
for df in dataframes:
    replace_nan(df, 'g','rating')

# Aplicar la funcion replace_nan a la columna duration de cada DataFrame en la lista para una funcion posterior (dado que daba error y esta fue mi forma de corregirlo)
    replace_nan(df, '0 min','duration')

Los campos de texto deberán estar en **minúsculas**, sin excepciones

In [7]:
def lowercase(dataframe: pd.DataFrame):
    """
    Convierte todos los campos de texto en minúsculas en un DataFrame.
    """
    for col in dataframe.select_dtypes(include=['object']):
        dataframe[col] = dataframe[col].str.lower()

dataframes = [lowercase(df) for df in dataframes]

El campo ***duration*** debe convertirse en dos campos: **`duration_int`** y **`duration_type`**.
El primero será un integer y el segundo un string indicando la unidad de medición de duración: min (minutos) o season (temporadas)

In [9]:
def split_duration(dataframe: pd.DataFrame):
    # Extraer el número y la unidad de medida de la columna 'duration'    
    dataframe[['duration_int', 'duration_type']] = dataframe['duration'].str.extract(r'(\d+)\s*([a-zA-Z]+)')
    # Convertir la columna 'duration_int' a tipo 'int'
    dataframe['duration_int'] = dataframe['duration_int'].astype(int)
    return dataframe

# Aplicar la función a cada DataFrame en la lista 'dataframes'
dataframes = [split_duration(df) for df in dataframes]

Reemplazamos la palabra "seasons" por la palabra "season" en la columna "duration_type" para que tenga consistencia con los otros valores.

In [10]:
def replace_str(dataframe: pd.DataFrame, old_value: str, new_value: str, column: str):
    """
    Reemplaza los valores indicados en una columna especificada del DataFrame con un valor especificado.
    """
    dataframe[column] = dataframe[column].replace(old_value, new_value)
    


# Aplicar la función replace_str a cada DataFrame en la lista
for df in dataframes:
    replace_str(df, 'seasons','season','duration_type')

Creamos la columna "platform", para facilitarnos las busquedas que fueron solicitadas (sé que hay otras formas pero esta es la forma que se me ocurrió)

In [11]:
for df, platform in zip(dataframes, platforms):
    df["platform"] = platform

creamos un Dataframe con todos los datos modificados y lo exportamos a csv para pode trabajarlo mas cómodo

In [12]:
final_df = pd.concat(dataframes, ignore_index=True)
final_df.to_csv(r'Datasets/final_df.csv')

vistazo final para ver cómo quedó nuestro hijo:

In [13]:
final_df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score,id,duration_int,duration_type,platform
0,s1,movie,dick johnson is dead,kirsten johnson,NaN,united states,2021-09-25,2020,pg-13,90 min,documentaries,"as her father nears the end of his life, filmm...",29,ns1,90,min,netflix
1,s2,tv show,blood & water,NaN,"ama qamata, khosi ngema, gail mabalane, thaban...",south africa,2021-09-24,2021,tv-ma,2 seasons,"international tv shows, tv dramas, tv mysteries","after crossing paths at a party, a cape town t...",86,ns2,2,season,netflix
2,s3,tv show,ganglands,julien leclercq,"sami bouajila, tracy gotoas, samuel jouy, nabi...",NaN,2021-09-24,2021,tv-ma,1 season,"crime tv shows, international tv shows, tv act...",to protect his family from a powerful drug lor...,75,ns3,1,season,netflix
3,s4,tv show,jailbirds new orleans,NaN,NaN,NaN,2021-09-24,2021,tv-ma,1 season,"docuseries, reality tv","feuds, flirtations and toilet talk go down amo...",49,ns4,1,season,netflix
4,s5,tv show,kota factory,NaN,"mayur more, jitendra kumar, ranjan raj, alam k...",india,2021-09-24,2021,tv-ma,2 seasons,"international tv shows, romantic tv shows, tv ...",in a city of coaching centers known to train i...,92,ns5,2,season,netflix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,s9664,movie,pride of the bowery,joseph h. lewis,"leo gorcey, bobby jordan",NaN,NaN,1940,7+,60 min,comedy,new york city street principles get an east si...,7,as9664,60,min,amazon
22994,s9665,tv show,planet patrol,NaN,"dick vosburgh, ronnie stevens, libby morris, m...",NaN,NaN,2018,13+,4 seasons,tv shows,"this is earth, 2100ad - and these are the adve...",49,as9665,4,season,amazon
22995,s9666,movie,outpost,steve barker,"ray stevenson, julian wadham, richard brake, m...",NaN,NaN,2008,r,90 min,action,"in war-torn eastern europe, a world-weary grou...",68,as9666,90,min,amazon
22996,s9667,tv show,maradona: blessed dream,NaN,"esteban recagno, ezequiel stremiz, luciano vit...",NaN,NaN,2021,tv-ma,1 season,"drama, sports","the series tells the story of diego maradona, ...",72,as9667,1,season,amazon
22997,s9668,movie,harry brown,daniel barber,"michael caine, emily mortimer, joseph gilgun, ...",NaN,NaN,2010,r,103 min,"action, drama, suspense","harry brown, starring two-time academy award w...",30,as9668,103,min,amazon